version: 2.0
workflows:
    version: 2
    test:
        jobs:
            - unit-3.5
            - unit-3.6
            - unit-3.7
            - style-check
jobs:
    unit-3.5: &test-template
        docker:
            - image: circleci/python:3.5
        working_directory: ~/pyshgp
        steps:
            - checkout
            - run:
                  name: Create venv
                  command: |
                      python3 -m venv venv
                      source venv/bin/activate
                      pip install -U pip
                      pip install -U setuptools
                      pip install -e .
            - run:
                name: Run unit tests
                command: |
                    source venv/bin/activate
                    python setup.py test
    unit-3.6:
        <<: *test-template
        docker:
            - image: circleci/python:3.6
    unit-3.7:
        <<: *test-template
        docker:
            - image: circleci/python:3.7
    style-check:
        docker:
            - image: circleci/python:latest
        working_directory: ~/pyshgp
        steps:
            - checkout
            - run:
                  name: Create venv
                  command: |
                      python3 -m venv venv
                      source venv/bin/activate
                      pip install -U pip
                      pip install flake8
                      pip install flake8-docstrings
            - run:
                  name: Run style checker
                  command: |
                      source venv/bin/activate
                      python -m flake8 pyshgp/
                      python -m flake8 examples/


