name: Test PyshGP Action

on: [push]

jobs:
  build:
    
    name: Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
      id: hello
    - name: Run a another
      run: echo 'The time was ${{ steps.hello.outputs.time }}.'
